### ISSUE TITLE
Bounce processing not setting  (Drupal) CiviCRM 'on hold' status

### ISSUE THREAD

**Issue by mfuggle** [JMAConsulting/biz.jmaconsulting.mte#76] opened 2015-01-14 23:48 UTC
I have read previous posts that suggest bounce processing is performing correctly using version 1.5 of the CivicCRM extension with the latest versions of CiviCRM in Drupal. I can see a number of  hard bounces on the Mandrill website. However they are not being picked up in CiviCRM so that the email addresses are placed 'on hold'. This is critical functionality for us. Unsubscribes are working correctly but not bounces. We have not received any soft bounces so I am not sure how they are managed.

I would really appreciate some help with this matter because I am unsure where I might be going wrong.

Cheers
Martin Fuggle

**Comment by mfuggle** [comment] 2015-01-15 00:00
I have started to get a better understanding of this and the hard bounces are not getting into the CiviCRM bounce mailbox from which CiviCRM can then set the 'on hold' status. So the problem is not as previously described but I need to understand how to get the bounce emails into the bounce mailbox.

Cheers
Martin

**Comment by Edzelopez** [comment] 2015-01-23 11:34
Hi @mfuggle 

Could you tell me a bit more about the configuration for bounce processing you have added in CiviCRM?

Thanks,
Edsel

**Comment by mfuggle** [comment] 2015-01-24 08:13
Hi @Edzelopez

Thanks for getting back to me. I have attached the CiviCRM Bounce Mail account, a delivery summary where there were approximately 20 bounces but none shown on the delivery summary, the Bounce email from Mandrill and the attachment to that email.

I have been over this a number of times and cannot see where I am going wrong.

Cheers
Martin Fuggle
![bounce - account](https://cloud.githubusercontent.com/assets/1777429/5886629/f6f04f24-a3fc-11e4-9b54-7e459697425c.png)
![bounce - delivery summary](https://cloud.githubusercontent.com/assets/1777429/5886630/f6f6e118-a3fc-11e4-80c5-81d311b20d24.png)
![bounce - mail attachment](https://cloud.githubusercontent.com/assets/1777429/5886632/f6fdb7cc-a3fc-11e4-8604-236521162e4e.png)
![bounce - mandrill sample email](https://cloud.githubusercontent.com/assets/1777429/5886631/f6fd6038-a3fc-11e4-851d-f867db605697.png)




Martin Fuggle

**Comment by JoeMurray** [comment] 2015-02-17 16:17
Hi Martin,

Mandrill Transactional Emails is an extension designed to integrate all transactional email from CiviCRM with Mandrill. CiviMail is for bulk sending, and was not part of the original scope. We have a new version that supports both CiviMail and transactional email. Would you be willing to help test it?

**Comment by mfuggle** [comment] 2015-02-19 00:29
Hi Joe,

How confident are you of the new version since I would need to test it 
in my production site (OK I hear you say - that's not ideal!). I can try 
it on a small distribution list to test the bounce processing.

Cheers...

*Martin Fuggle*
kew: 03 9817 1041 <tel:0398171401>
mobile: 04 0826 5586 <tel:0408265586>
skype: mfuggle <callto:mfuggle>
website www.martinfuggle.com <http://www.martinfuggle.com>

**Comment by mfuggle** [comment] 2015-02-19 02:42
Hi Joe,

I installed the 1.5 beta version and sent an email via CiviEmail to two 
people, one whose email is valid and one whose email generated a hard 
bounce. The result is as follows:

  * Mandrill shows the hard bounce on its webpage
  * The bounce email has been received in the bounce email address
  * Civimail states that 0/119 have been ignored but 0/0 have been processed

(see the two attached screen shots)

As a result of the above there are no bounces shown in the CiviMail 
report and the email address has not been placed On Hold.

Unfortunately I am not a programmer but it seems to me that CiviMail is 
not parsing the bounce email correctly. So either CiviMail is incorrect 
or the email being received from Mandrill is of a form that is not 
understood by CiviMail.

Anyway that's my take on whats happening.
*Martin Fuggle*
kew: 03 9817 1041 <tel:0398171401>
mobile: 04 0826 5586 <tel:0408265586>
skype: mfuggle <callto:mfuggle>
website www.martinfuggle.com <http://www.martinfuggle.com>
Returned email...



Civimail showing 0/119 ignored, but 0/0 processed...

**Comment by JoeMurray** [comment] 2015-02-19 14:57
This is the expected behaviour when trying to use our extension and CiviMail, since the extension doesn't support that properly. The next version of the extension will support this. Testing it on a small distribution list on your production system should be a good way to test it. We'll ping you when it is ready shortly.

**Comment by mfuggle** [comment] 2015-02-20 01:00
Hi Joe,

I must have missed something. I read the attached about the latest 
(beta) release which states that the code had been fixed 'to set on-hold 
email after bounce threshold' is exceeded.



*Martin Fuggle*
kew: 03 9817 1041 <tel:0398171401>
mobile: 04 0826 5586 <tel:0408265586>
skype: mfuggle <callto:mfuggle>
website www.martinfuggle.com <http://www.martinfuggle.com>

**Comment by herbdool** [comment] 2015-03-02 16:03
Hi Joe, I think I'd be willing to test it. Is it a branch on this repo?

**Comment by danielstrum** [comment] 2015-03-16 21:30
Hi Joe,

I would definitely be willing to help test the new version with support for CiviMail. I assume the worst case scenario is that the return channel would not work (emails would be sent), right? 

I have 2 client that I would use this for right away. Thanks for your work.

**Comment by shawnholt** [comment] 2015-03-18 17:15
I started a new thread: #80 specifically on bulk email support.  @JoeMurray with your permission, would like to focus specifically on that topic in new thread and if appropriate, close this one.

**Comment by JoeMurray** [comment] 2015-03-18 18:59
Agreed.

**Closed by JoeMurray** 2015-03-18 18:59 UTC
